loop around dotnet test

diff --git a/.github/workflows/most-basic-run.yml b/.github/workflows/most-basic-run.yml
--- a/.github/workflows/most-basic-run.yml
+++ b/.github/workflows/most-basic-run.yml
@@ -20,5 +20,23 @@ jobs:
     - name: Restore, Build & Test
       run: |        
         dotnet build
-        dotnet test --no-build --logger:"junit;LogFilePath=test-output.xml"
+        #dotnet test --no-build --filter TestCategory=\"IncludeFailures\" --logger:"junit;LogFilePath=test-output.xml"
+
+        function run_tests_with_retry() {
+          local attempt=0
+          local max_attempts=5
+          until [ $attempt -ge $max_attempts ]
+          do
+            dotnet test --no-build --filter TestCategory=\"IncludeFailures\" --logger:"junit;LogFilePath=test-output.xml" && break
+            attempt=$((attempt+1))
+            echo "Retrying dotnet test... Attempt $attempt/$max_attempts"
+          done
+
+          if [ $attempt -eq $max_attempts ]; then
+            echo "Tests failed after $max_attempts attempts."
+            exit 1
+          fi
+        }
+
+        run_tests_with_retry
 
